# SPDX-FileCopyrightText: 2020-2022 Gilles Caulier <caulier dot gilles at gmail dot com>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules':   '@stable'
    'frameworks/kxmlgui':               '@stable'
    'frameworks/kcoreaddons':           '@stable'
    'frameworks/kconfig':               '@stable'
    'frameworks/kservice':              '@stable'
    'frameworks/kwindowsystem':         '@stable'
    'frameworks/solid':                 '@stable'
    'frameworks/ki18n':                 '@stable'
    'frameworks/kio':                   '@stable'
    'frameworks/kiconthemes':           '@stable'
    'frameworks/threadweaver':          '@stable'
    'frameworks/knotifications':        '@stable'
    'frameworks/kcalendarcore':         '@stable'
    'frameworks/kimageformats':         '@stable'

- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/knotifyconfig':         '@stable'

- 'on': ['FreeBSD']
  'require':
    'graphics/libksane':                '@stable'
    'frameworks/kcontacts':             '@stable'
    'pim/akonadi-contacts':             '@stable'
    'frameworks/kfilemetadata':         '@stable'

Options:
    run-cppcheck: False
    use-ccache:   True
    require-passing-tests-on: [ 'Linux' ]
