
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:55 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:55 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      Build started 06-07-2023 10:45:33.
      
      Project "C:\\digikamclone\\digikam\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\digikamclone\\digikam\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\digikamclone\\digikam\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:02.17
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/digikamclone/digikam/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:55 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      Build started 06-07-2023 10:45:36.
      
      Project "C:\\digikamclone\\digikam\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\digikamclone\\digikam\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\digikamclone\\digikam\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.35
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/digikamclone/digikam/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:55 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-uwebfy"
      binary: "C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-uwebfy"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-uwebfy
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_bf69c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        Build started 06-07-2023 10:45:39.
        
        Project "C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-uwebfy\\cmTC_bf69c.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_bf69c.dir\\Debug\\".
          Creating directory "C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-uwebfy\\Debug\\".
          Creating directory "cmTC_bf69c.dir\\Debug\\cmTC_bf69c.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_bf69c.dir\\Debug\\cmTC_bf69c.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_bf69c.dir\\Debug\\\\" /Fd"cmTC_bf69c.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Users\\user\\Downloads\\cmake-3.26.3-windows-x86_64\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_bf69c.dir\\Debug\\\\" /Fd"cmTC_bf69c.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Users\\user\\Downloads\\cmake-3.26.3-windows-x86_64\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-uwebfy\\Debug\\cmTC_bf69c.exe" /INCREMENTAL /ILK:"cmTC_bf69c.dir\\Debug\\cmTC_bf69c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-uwebfy/Debug/cmTC_bf69c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-uwebfy/Debug/cmTC_bf69c.lib" /MACHINE:X64  /machine:x64 cmTC_bf69c.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_bf69c.vcxproj -> C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-uwebfy\\Debug\\cmTC_bf69c.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_bf69c.dir\\Debug\\cmTC_bf69c.tlog\\unsuccessfulbuild".
          Touching "cmTC_bf69c.dir\\Debug\\cmTC_bf69c.tlog\\cmTC_bf69c.lastbuildstate".
        Done Building Project "C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-uwebfy\\cmTC_bf69c.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.34
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/user/Downloads/cmake-3.26.3-windows-x86_64/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:55 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-d4qvb7"
      binary: "C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-d4qvb7"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-d4qvb7
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_c3066.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        Build started 06-07-2023 10:45:41.
        
        Project "C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-d4qvb7\\cmTC_c3066.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_c3066.dir\\Debug\\".
          Creating directory "C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-d4qvb7\\Debug\\".
          Creating directory "cmTC_c3066.dir\\Debug\\cmTC_c3066.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_c3066.dir\\Debug\\cmTC_c3066.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c3066.dir\\Debug\\\\" /Fd"cmTC_c3066.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Users\\user\\Downloads\\cmake-3.26.3-windows-x86_64\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c3066.dir\\Debug\\\\" /Fd"cmTC_c3066.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Users\\user\\Downloads\\cmake-3.26.3-windows-x86_64\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-d4qvb7\\Debug\\cmTC_c3066.exe" /INCREMENTAL /ILK:"cmTC_c3066.dir\\Debug\\cmTC_c3066.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-d4qvb7/Debug/cmTC_c3066.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/digikamclone/digikam/CMakeFiles/CMakeScratch/TryCompile-d4qvb7/Debug/cmTC_c3066.lib" /MACHINE:X64  /machine:x64 cmTC_c3066.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_c3066.vcxproj -> C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-d4qvb7\\Debug\\cmTC_c3066.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_c3066.dir\\Debug\\cmTC_c3066.tlog\\unsuccessfulbuild".
          Touching "cmTC_c3066.dir\\Debug\\cmTC_c3066.tlog\\cmTC_c3066.lastbuildstate".
        Done Building Project "C:\\digikamclone\\digikam\\CMakeFiles\\CMakeScratch\\TryCompile-d4qvb7\\cmTC_c3066.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.31
        
      exitCode: 0
...
